blank_issues_enabled: false

contact_links:
  - name: General ArcOS Help
    url: https://discord.gg/ARjRM6uNqf
    about: If you need help using or setting up ArcOS, you can head to the Official Discord server for help.
